name: 'linkaster-front-only'

services:
  # Front-end service
  flutter-web:
    build: 
      context: ../linkaster_application
      dockerfile: Dockerfile
    ports:
      - "8077:77"
    restart: unless-stopped