name: 'linkaster-front-only'

#
#  Title: docker-compose-frontonly.yml
#  Author: Ortega Mendoza, Javier
#  Date: 2024
#  Code Version: 1.0
#  Availability: https://github.com/javsort/Linkaster
#

services:
  # Front-end service
  flutter-web:
    build: 
      context: ../linkaster_application
      dockerfile: Dockerfile
    ports:
      - "8077:80"
    restart: unless-stopped